version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: frigate-monitor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=America/Sao_Paulo
    shm_size: '1gb'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: http://backend:8000
    container_name: frigate-monitor-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
