version: '3.9'

services:
  backend:
    build:
      context: ./backend
    image: frigate-monitor-backend
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=/data
    volumes:
      - ./data:/data
      - ./backend/app:/app/app:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: frigate-monitor-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000
    ports:
      - "5173:4173"
    restart: unless-stopped
